spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: <tenant-id>
        credential:
          client-id: <client-id>
          client-secret: <client-secret>
        redirect-uri-template: http://localhost:880/redirect

server:
  port: 8080
  forward-headers-strategy: native